In [4]:
import cv2

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)
while True:
    _, frame = cap.read()
    hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    height, width, _ = frame.shape
    cx= int(width / 2)
    cy= int(height / 2)
    pixel_center= hsv_frame[cy, cx]
    hue_value= pixel_center[0]

    if hue_value < 5:
        color= "Red"
    elif 5 < hue_value < 20:
        color= "Orange"
    elif 20 < hue_value < 30:
        color= "Yellow"
    elif 30 < hue_value < 85:
        color= "Green"
    elif 85 < hue_value < 125:
        color= "Blue"
    elif 125 < hue_value < 170:
        color= "Purple"
    else:
        color= "Red"        
    cv2.putText(frame, color, (10, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,0), 2)
    print(pixel_center)
    cv2.circle(frame, (cx, cy), 5, (255,0,0), 3)
    cv2.imshow("Image", frame)
    key= cv2.waitKey(1)
    if key==27:
        break
cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)



[  7  78 127]
[  4  93 132]
[  4  93 134]
[  5  97 134]
[  5  97 131]
[  5  98 130]
[  5  98 130]
[  5  99 129]
[  4  95 129]
[  5  99 129]
[  5 100 132]
[  5 100 132]
[  5 100 133]
[  5  99 134]
[  5  99 134]
[  5  99 134]
[  5  98 135]
[  6 100 138]
[  6 100 138]
[  6  98 140]
[  5 100 143]
[  5  99 144]
[  6 100 146]
[  6 103 144]
[  6 100 146]
[  6  98 148]
[  7 102 152]
[  6 100 155]
[  6 101 156]
[  6 100 155]
[  6 100 155]
[  6 100 155]
[  7 106 166]
[  7 106 168]
[  7 106 169]
[  7 106 169]
[  7 108 174]
[  7 108 174]
[  7 113 173]
[  8 112 177]
[  8 108 177]
[  8 109 176]
[  8 111 175]
[  8 112 175]
[  8 109 176]
[  8 112 175]
[  7 110 178]
[  7 108 175]
[  8 109 176]
[  7 110 178]
[  8 109 176]
[  8 111 175]
[  8 111 175]
[  8 112 175]
[  7 109 177]
[  7 109 177]
[  8 111 174]
[  8 111 174]
[  8 111 174]
[  8 111 175]
[  9 109 173]
[  8 111 174]
[  8 111 175]
[  8 109 176]
[  8 109 176]
[  8 112 175]
[  8 112 175]
[  8 112 175]
[  8 112 175]
[  8 111 175]
[  7 106 176]
[  7 1

-1

In [5]:
import cv2
import numpy as np

cap = cv2.VideoCapture(0)
cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

while True:
    _, frame = cap.read()
    hsv_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    height, width, _ = frame.shape
    cx = int(width / 2)
    cy = int(height / 2)
    pixel_center = hsv_frame[cy, cx]
    hue, sat, val = pixel_center

    # Determine color
    if val < 50:
        color = "Black"
    elif hue < 5:
        color = "Red"
    elif 5 <= hue < 20:
        color = "Orange"
    elif 20 <= hue < 30:
        color = "Yellow"
    elif 30 <= hue < 85:
        color = "Green"
    elif 85 <= hue < 125:
        color = "Blue"
    elif 125 <= hue < 150:
        color = "Purple"
    elif 150 <= hue < 170:
        color = "Pink/Peach"
    else:
        color = "Red"

    cv2.putText(frame, color, (10, 50), cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 0), 2)
    cv2.circle(frame, (cx, cy), 5, (255, 0, 0), 3)
    cv2.imshow("Image", frame)
    
    key = cv2.waitKey(1)
    if key == 27:  # ESC to exit
        break

cap.release()
cv2.destroyAllWindows()
cv2.waitKey(1)


-1

In [1]:
import cv2
print(cv2.__version__)


4.12.0
