In [1]:
import cv2 as cv
import numpy as np
import sys

In [20]:
def findClickPosition(needle_img_path, haystack_img_path, threshold=0.5, debug_mode=None):
        
    haystack_img = cv.imread(haystack_img_path, cv.IMREAD_COLOR)
    needle_img = cv.imread(needle_img_path, cv.IMREAD_COLOR)

    #get the width and height of the needle image to draw the rectangle
    needle_w = needle_img.shape[1]
    needle_h = needle_img.shape[0]

    #match Template is used to match a small image in a larger image
    #they are 6 methods available for template matching in OpenCV
    method = cv.TM_CCOEFF_NORMED
    result = cv.matchTemplate(haystack_img, needle_img, method)
    
    
    #get the locations where the matching result is less than the threshold
    #zip the locations into a list of (x, y) coordinates , the total number of simlar images found
    locations= np.where(result >= threshold)
    locations = list(zip(*locations[::-1]))

    #create rectangles for each location found
    rectangles=[]
    for loc in locations:
        rect = [int(loc[0]), int(loc[1]), needle_w, needle_h]
        rectangles.append(rect)
        rectangles.append(rect)  #we need to add the same rectangle twice to group them later

    #group the rectangles to avoid multiple overlapping rectangles for the same area
    rectangles, weights=cv.groupRectangles(rectangles, groupThreshold=1, eps=0.05)
    print(rectangles)
    points = []
    #draw the rectangles on the haystack image
    if locations:
        print("Needle found in haystack!")
        line_color = (0, 255, 0)
        line_type = cv.LINE_4
        for (x, y, w, h) in rectangles:

            # To draw the center of the rectangle
            center_x = x + int(w // 2)
            center_y = y + int(h // 2)
            points.append((center_x, center_y))
            if debug_mode == 'rectangles':
                top_left = (x, y)
                bottom_right = (x+w, y+h)
                cv.rectangle(haystack_img,top_left , bottom_right, line_color, lineType=line_type)
            elif debug_mode == 'points':
                cv.drawMarker(haystack_img, (center_x, center_y), color=line_color, markerType=cv.MARKER_CROSS, markerSize=40, thickness=2, line_type=line_type)
        if debug_mode:
            cv.imshow('Matches', haystack_img)
            cv.waitKey(0)
            cv.destroyAllWindows()  
            cv.waitKey(1)
    return points

points = findClickPosition('data/needle1.png', 'data/farm_villa.jpg',threshold=0.65, debug_mode='points')
print(points)
points = findClickPosition('data/needle.jpg', 'data/farm_villa.jpg',threshold=0.49, debug_mode='rectangles')
print(points)

 

[[  42   48   48   20]
 [  41   52   48   20]
 [  39   56   48   20]
 [ 441  109   48   20]
 [ 520  180   48   20]
 [ 550  214   48   20]
 [ 770  228   48   20]
 [ 685  272   48   20]
 [ 640  295   48   20]
 [1236  336   48   20]
 [1860  342   48   20]
 [1862  351   48   20]
 [1234  358   48   20]
 [1203  442   48   20]
 [  41  465   48   20]
 [ 662  656   48   20]
 [ 933  681   48   20]]
Needle found in haystack!
[(np.int32(66), np.int32(58)), (np.int32(65), np.int32(62)), (np.int32(63), np.int32(66)), (np.int32(465), np.int32(119)), (np.int32(544), np.int32(190)), (np.int32(574), np.int32(224)), (np.int32(794), np.int32(238)), (np.int32(709), np.int32(282)), (np.int32(664), np.int32(305)), (np.int32(1260), np.int32(346)), (np.int32(1884), np.int32(352)), (np.int32(1886), np.int32(361)), (np.int32(1258), np.int32(368)), (np.int32(1227), np.int32(452)), (np.int32(65), np.int32(475)), (np.int32(686), np.int32(666)), (np.int32(957), np.int32(691))]
[[514 483  62  48]
 [638 494  62  48]
 